name: My primera integracion

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.0

      - name: Verificacion de la version de flutter
        run: bash ./scripts/check_flutter_version.sh

      - name: Restore cache
        uses: actions/cache@v6
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}

      - run: flutter pub get

      - name: Verificacion de calidad de codigo
        run: dart format --output=none --set-exit-if-changed .

      - name: Analisis estatico
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - run: echo "Finalizando la integracion continua"

  build_android:
    needs: validation
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.0

      - name: Verificacion de la version de flutter
        run: bash ./scripts/check_flutter_version.sh

      - run: flutter pub get

      - run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: android-device-validation-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  device_validation:
    needs: build_android
    runs-on: [self-hosted, macos, test-android]

    environment:
      name: physical-device

    steps:
      - name: Download APK
        uses: actions/download-artifact@v8
        with:
          name: android-device-validation-apk
          path: ./artifacts

      - name: List artifact
        run: |
          find ./artifacts -type f

      - name: Check Android device
        run: adb devices

      



