name: test secrets

on:
  push:

jobs:
  test_secrets:
    runs-on: ubuntu-latest

    environment: Development

    env:
      KEY_SECRET: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Imprimir secretos
        run: echo "${{ secrets.SECRET_KEY }} " 




