name: maquina local

on:
  push:

  workflow_dispatch:


jobs:
  self-hosted:
    runs-on: [self-hosted, macos, ecz-android]


    steps:
      - run: echo "prueba runner"
      - run: cd ..
      - run: mkdir hola-mundo
